### ISSUE TITLE
Include python bindings from CMS

### ISSUE THREAD

**Issue by DrDaveD** [fermitools/frontier#37]
CMS adds frontier client python bindings in [this directory](https://github.com/cms-externals/frontier_client/tree/cms/2.9.1/python).  Add them to the frontier client itself and copy them into the install dir during make dist.

**Comment by DrDaveD** [comment]
Also include the patch from cms-externals/frontier_client#2

**Comment by cvuosalo** [comment]
frontier_client 2.10.1 has been released. It includes the Python bindings and the patch. I think this issue can be closed.
